import { createContext } from "react"; // First Step is import
const noteContext= createContext(); // in this notecontext we will store all the context related values of note in this... 
export default noteContext;